istio remote 설치, EFS restore
OpsNow/kops-cui pull request #309
Opened 2019-02-22 06:39 UTC by gelius7

istio remote 설치
EFS fs-id 를 입력받아서 이미 있으면 있는 EFS 를 사용하도록

2019-02-22 08:47 UTC, nalbam requested changes

2019-02-22 08:47 UTC, nalbam commented on helm.sh
> +    EFS_ID=${ANSWER}
EFS_ID 는 환경 변수에서 받아와요.
그게 있는지 부터 확인하는게 좋을것 같아요.
변경을 원할수도 있으니...
default 값에 기존에 있던 EFS_ID 를 넣어주고.
그냥 엔터 치면.. 기존걸로.. 새거 입력 하면 그걸로...

2019-02-22 09:16 UTC, gelius7 commented on helm.sh
> +    EFS_ID=${ANSWER}
반영하였습니다.

2019-02-26 08:31 UTC, nalbam approved these changes

2019-02-26 08:31 UTC, merged