efs-pvc-exporter chart yaml 구성 변경 및 helm.sh 수정
OpsNow/kops-cui pull request #376
Opened 2019-05-30 07:03 UTC by longlg88

chart yaml 구성 변경
- static한 값들을 values.yaml로 이동(schedule / restart policy)
- 사용하지 않는 parameter 제거
- cluster role / cluster role binding 시 naming을 다음과 같이 변경
  - Cluster role ==> valve:[Values yaml에 정의된 rolename]
  - Cluster role binding ==> valve:[Values yaml에 정의된 rolename]:[Service Account name]

helm.sh 수정
- efs-pvc-exporter 차트가 있을 때 parameter를 받을 수 있도록 정의(schedule / restart policy)

2019-05-30 09:09 UTC, gelius7 approved these changes
확인했습니다.

2019-05-31 02:02 UTC, nalbam requested changes

2019-05-31 02:02 UTC, nalbam commented on helm.sh
> +        _replace "s/AWS_REGION/${REGION}/g" ${CHART}
요것도 필요한가요? 리전 변경 될곳이 없으면 지우셔도...

2019-05-31 02:02 UTC, nalbam commented on helm.sh
> +
빈라인은 한줄로 해주시면 안되나요? ㅠㅠ

2019-05-31 02:15 UTC, longlg88 commented on helm.sh
> +
빈라인 한줄로 처리했습니당!

2019-05-31 02:15 UTC, longlg88 commented on helm.sh
> +        _replace "s/AWS_REGION/${REGION}/g" ${CHART}
리전 변경 지웠고 elasticsearch-snapshot에서도 지웠습니다!

2019-05-31 02:16 UTC, nalbam approved these changes

2019-05-31 02:16 UTC, merged