Add alert for checking apps and alarm
OpsNow/kops-cui pull request #379
Opened 2019-06-12 01:32 UTC by longlg88

코러산트 환경에서 운영되는 
- Pod가 5분 이상 서비스 불능 상태인 경우
- Pod의 Node가 서비스 불능 상태인 경우
- Pod의 App들의 서비스가 평균 응답시간이 5분동안 5초를 넘는 경우
- Max HPA 값을 사용하고 있는 Pod 확인

추가로 group interval을 3h --> 8h 수정(빈번한 알람 방지) // 이는 환경마다 변경이 되어야 함.

2019-06-12 01:58 UTC, gelius7 requested changes
이번 수정에 각 알람마다 클러스터 이름이 prefix 로 나오기 바랍니다.
ex) [OKC2] Node xxxx is failed. Check node!!
어떤 클러스터에서 발생한 알람인지 알고 싶습니다.

2019-06-12 02:04 UTC, longlg88 commented
확인했습니다. 클러스터명을 넣을 수 있는 방안 모색합니다.

2019-06-18 02:00 UTC, longlg88 commented
클러스터명을 넣을 방법을 찾지 못했습니다. ㅠㅠ values.yaml에 넣은 예제가 없네요.

2019-06-27 00:48 UTC, longlg88 commented
'CLUSTER_NAME' 변수를 helm chart 생성 전에 맵핑을 해주고 있어, 이를 활용할 수 있습니다.
찬규님의 commit을 이용하여 최종 commit 하겠습니다.

2019-06-27 01:44 UTC, gelius7 approved these changes
확인했습니다.

2019-06-27 09:01 UTC, pakisto approved these changes
commit

2019-06-27 09:02 UTC, merged