Tools update
OpsNow/kops-cui pull request #381
Opened 2019-06-19 05:58 UTC by longlg88

tools.sh - awscli 를 설치하기 위한 linux 설치법 변경
kops.sh - aws configure가 설정되지 않았을 때 방어 로직 추가

2019-06-20 07:11 UTC, nalbam requested changes
탭 말고 스페이스 4 자리로 해주세요. ^^
라인뒤 공백도 없었으면 좋겠네요.

2019-06-20 08:16 UTC, longlg88 commented
네 감사합니다! 수정하겠습니다!

2019-07-02 05:58 UTC, gelius7 approved these changes
ok

2019-07-02 05:59 UTC, gelius7 approved these changes
ok

2019-07-02 06:11 UTC, pakisto approved these changes
ok

2019-07-02 06:12 UTC, nalbam approved these changes

2019-07-02 06:12 UTC, nalbam commented on kops.sh
> +	aws s3 ls 2>temp
요기도 탭...

2019-07-02 06:13 UTC, merged