upgrade grafana 3.0.4 to 3.5.10 values.yaml / modify dashboard labs url
OpsNow/kops-cui pull request #386
Opened 2019-07-12 01:56 UTC by longlg88

grafana helm chart version 업그레이드
dashboard id가 정열님 것으로 되어있었는데 이를 bespinsre 계정으로 변경

2019-07-12 02:20 UTC, nalbam requested changes

2019-07-12 02:20 UTC, nalbam commented on charts/monitor/grafana.yaml
>        # https://grafana.com/dashboards/9679
요것도 10516 로 바꾸셔야.. ㅎㅎ

2019-07-12 02:33 UTC, longlg88 commented on charts/monitor/grafana.yaml
>        # https://grafana.com/dashboards/9679
수정했습니다.

2019-07-12 02:35 UTC, nalbam approved these changes

2019-07-15 01:22 UTC, pakisto approved these changes

2019-07-15 01:22 UTC, merged